/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibapplikation;


import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author strom
 */
public class WindowAdminDeleteAgent extends javax.swing.JFrame {


    private InfDB idb;

    /**
     * Creates new form WindowAlienChangePw
     */
    public WindowAdminDeleteAgent(InfDB idb) {
        initComponents();
        this.idb= idb;
        jpInfo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblAgent = new javax.swing.JLabel();
        txtfAgentInput = new javax.swing.JTextField();
        jpInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaPrintInfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaTitleInfo = new javax.swing.JTextArea();
        btnChangeInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Galaxal");
        setBackground(new java.awt.Color(40, 40, 40));
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(40, 40, 40));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Ta bort agent");

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 96, 96));
        lblMessage.setText(" ");

        btnDelete.setText("TA BORT");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMenu.setText("MENY");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblAgent.setForeground(new java.awt.Color(255, 255, 255));
        lblAgent.setText("Ange agentens namn eller id:");

        txtfAgentInput.setColumns(6);

        jpInfo.setBackground(new java.awt.Color(79, 79, 79));
        jpInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtaPrintInfo.setBackground(new java.awt.Color(40, 40, 40));
        txtaPrintInfo.setColumns(20);
        txtaPrintInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtaPrintInfo.setRows(5);
        txtaPrintInfo.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtaPrintInfo);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtaTitleInfo.setBackground(new java.awt.Color(40, 40, 40));
        txtaTitleInfo.setColumns(20);
        txtaTitleInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtaTitleInfo.setRows(5);
        txtaTitleInfo.setText("Följande område behöver tilldelas \nen ny områdeschef innan agenten\nkan tas bort");
        txtaTitleInfo.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(txtaTitleInfo);

        btnChangeInfo.setText("Ändra områdeschef");
        btnChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInfoLayout = new javax.swing.GroupLayout(jpInfo);
        jpInfo.setLayout(jpInfoLayout);
        jpInfoLayout.setHorizontalGroup(
            jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangeInfo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpInfoLayout.setVerticalGroup(
            jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeInfo)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfAgentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(btnDelete)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMenu)))
                .addGap(18, 18, 18)
                .addComponent(jpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAgent)
                        .addGap(12, 12, 12)
                        .addComponent(txtfAgentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(lblMessage)
                        .addGap(60, 60, 60)
                        .addComponent(btnMenu))
                    .addComponent(jpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getAgentId() {
        String agentId = "";
        try {
            String qAgentId = "SELECT agent_id FROM agent WHERE namn = '" + txtfAgentInput.getText() + "' OR agent_id = '" + txtfAgentInput.getText() + "'";
            String resultAgentId = idb.fetchSingle(qAgentId);
 
            if(resultAgentId != null){
                agentId = resultAgentId;
            }
            
        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }
  
        return agentId;
    }

    private boolean checkAgentDoublet() {
        int loops = 0;
        boolean isDoublet = false;
        try {
            String qAgentId = "SELECT agent_id FROM agent WHERE namn = '" + txtfAgentInput.getText() + "' OR agent_id = '" + txtfAgentInput.getText() + "'";
            ArrayList<String> agentIdList = idb.fetchColumn(qAgentId);


            for (String element : agentIdList) {
                loops++;
            }
            if(loops > 1 ){
                isDoublet = true;
            }
        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }
        System.out.println(isDoublet);
        return isDoublet;

    }

    private boolean checkAgentIsContact() {
        // Ta bort från agentlistan
        // Ta bort från fältagent, områdeschef, kontorschef
        // Ta bort från innahar_fordon
        // Ta bort från innehar_utrustning
        // Ändra ansvarig agent för alien KLAR
        txtaPrintInfo.setText("");
        String agentId = getAgentId();
        boolean isContactAgent = false;

        try {
            String qAlien = "SELECT alien_id, namn FROM alien WHERE ansvarig_agent = '" + agentId + "'";
            ArrayList<HashMap<String, String>> result = idb.fetchRows(qAlien);

            if (result.size() > 0) {

                txtaTitleInfo.setText("Följande aliens behöver tilldelas\n"
                        + "ny kontaktperson innan \n"
                        + "agenten kan tas bort");
                for (HashMap<String, String> element : result) {
                    txtaPrintInfo.append(" -" + element.get("alien_id") + " " + element.get("namn") + "\n");
                }
                btnChangeInfo.setText("Ändra info om alien");

                isContactAgent = true;
            }

        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }
        return isContactAgent;
    }

    private boolean checkAgentIsAreaChief() {
        txtaPrintInfo.setText("");
        String agentId = getAgentId();
        boolean isAreaChief = false;

        try {
            String qOmrade = "SELECT benamning FROM omrade o\n"
                    + "JOIN omradeschef oc ON o.omrades_id = oc.omrade\n"
                    + "WHERE agent_id = '" + agentId + "'";
            String result = idb.fetchSingle(qOmrade);

            if (result != null) {

                txtaTitleInfo.setText("Följande område behöver tilldelas \n"
                        + "en ny områdeschef innan agenten\n"
                        + "kan tas bort");
                txtaPrintInfo.append(" -" + result);
                btnChangeInfo.setText("Ändra områdeschef");

                isAreaChief = true;
            }

        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }
        return isAreaChief;
    }

    private void deleteAgent() {
        String agentId = getAgentId();

        try {
            String qVehicle = "DELETE FROM innehar_fordon WHERE agent_id = '" + agentId + "'";
            idb.delete(qVehicle);
            String qEquipment = "DELETE FROM innehar_utrustning WHERE agent_id = '" + agentId + "'";
            idb.delete(qEquipment);
            String qAreaChief = "DELETE FROM omradeschef WHERE agent_id = '" + agentId + "'";
            idb.delete(qAreaChief);
            String qHeadChief = "DELETE FROM kontorschef WHERE agent_id = '" + agentId + "'";
            idb.delete(qHeadChief);
            String qFieldAgent = "DELETE FROM faltagent WHERE agent_id = '" + agentId + "'";
            idb.delete(qFieldAgent);
            String qAgent = "DELETE FROM agent WHERE agent_id = '" + agentId + "'";
            idb.delete(qAgent);

        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }

    }


    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        lblMessage.setText(" ");
        lblMessage.setForeground(Color.RED);
        jpInfo.setVisible(false);

        if(Validation.validationTxt(txtfAgentInput, lblMessage, "Ange agentnamn eller id")){
            if (checkAgentDoublet()) {
                lblMessage.setText("Det finns mer än en agent med detta namn, vänligen ange id");

            } else if (getAgentId().equals("")) {
                lblMessage.setText("Agentnamnet eller id:t finns inte registrerat");

            } else if(checkAgentIsContact()){
                jpInfo.setVisible(true);
            } else if(checkAgentIsAreaChief()){
                jpInfo.setVisible(true);
            }else{
               deleteAgent();

                lblMessage.setForeground(Color.GREEN);
                lblMessage.setText("Agenten har tagits bort!");

            }
        }
 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        //dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInfoActionPerformed
        // TODO add your handling code here:
        if(btnChangeInfo.getText().equals("Ändra områdeschef")){
            new WindowAdminChangeAreaChief(idb).setVisible(true);
        }
         if(btnChangeInfo.getText().equals("Ändra info om alien")){
            new WindowAdminUpdateAlienInfo(idb).setVisible(true);
        }
    }//GEN-LAST:event_btnChangeInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnChangeInfo;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpInfo;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtaPrintInfo;
    private javax.swing.JTextArea txtaTitleInfo;
    private javax.swing.JTextField txtfAgentInput;
    // End of variables declaration//GEN-END:variables
}
