package Agent_and_Admin;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Panel som listar alla aliens på en vald plats
 *
 * @author Grupp 8
 */
public class JpListAlienLocation extends javax.swing.JPanel {

    private InfDB idb;

    public JpListAlienLocation(InfDB idb) {
        initComponents();
        this.idb = idb;
        // Metoden .setEditable(false) gör så att man endast kan "selecta" text och inte skriva i text arean.
        txtaShowAliens.setEditable(false);
        listAllLocations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectLocation = new javax.swing.JLabel();
        cbListLocations = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaShowAliens = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(40, 40, 40));

        lblSelectLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectLocation.setText("Välj en plats:");

        cbListLocations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----" }));
        cbListLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListLocationsActionPerformed(evt);
            }
        });

        txtaShowAliens.setBackground(new java.awt.Color(79, 79, 79));
        txtaShowAliens.setColumns(19);
        txtaShowAliens.setForeground(new java.awt.Color(255, 255, 255));
        txtaShowAliens.setRows(5);
        jScrollPane1.setViewportView(txtaShowAliens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbListLocations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectLocation)
                    .addComponent(cbListLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listAllLocations() {

        try {
            String query = "SELECT benamning FROM plats";
            ArrayList<String> listLocations = idb.fetchColumn(query);

            for (String element : listLocations) {

                cbListLocations.addItem(element);

            }
        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }
    }
    private void cbListLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListLocationsActionPerformed

        txtaShowAliens.setText("");

        try {

            String query = "SELECT namn, alien_id from Alien \n"
                    + "JOIN plats ON Alien.plats = plats.plats_ID\n"
                    + "WHERE benamning =" + "'" + cbListLocations.getSelectedItem() + "'";

            ArrayList<HashMap<String, String>> alienInfo = idb.fetchRows(query);

            txtaShowAliens.append("ID \t NAMN \n"
                    + "-------\t-------\n");

            for (HashMap<String, String> element : alienInfo) {
                txtaShowAliens.append(element.get("alien_id") + "\t " + element.get("namn") + "\n");

            }

        } catch (InfException ex) {
            System.out.println("Databasfel" + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Random fel" + ex.getMessage());
        }

    }//GEN-LAST:event_cbListLocationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbListLocations;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectLocation;
    private javax.swing.JTextArea txtaShowAliens;
    // End of variables declaration//GEN-END:variables
}
